spring:
  application:
    name: yak-spring

yak:
  caches:
    - name: intTest
      maximumKeys: 64
      fixedValueSize: 128
      valueStorageMechanism: "DirectMemoryStorage"
      evictionStrategy: "LRU"