global:
  scrape_interval: 15s
  external_labels:
    monitor: 'yak-monitor'

scrape_configs:

  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['prom:9090']

  - job_name: 'yak-server'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'yak-server:9001' ]