{
 "title": "Yak Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_used{instance=\"yak-server:9001\"}) by (area,instance)",
     "legendFormat": "used {{ area }}"
    },
    {
     "expr": "sum(jvm_memory_bytes_max{instance=\"yak-server:9001\"}) by (area,instance)",
     "legendFormat": "max {{ area }}"
    }
   ]
  },
  {
   "title": "Thread Health",
   "type": "graph",
   "description": "The thread heartbeat total for each thread within the application.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(thread_heartbeat_total[1m]) * 60) by (thread_name)",
     "legendFormat": "{{ thread_name }}"
    }
   ]
  },
  {
   "title": "Cache Hits",
   "type": "graph",
   "description": "Displays the cache hits for each cache over time.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cache_response_total[1m]) * 60) by (cache_name, response_type)",
     "legendFormat": "{{ cache_name }} - {{ response_type }}"
    }
   ]
  }
 ]
}