name: main-build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:
      DOCKER_LOGIN_PASSWORD: ${{ secrets.DOCKER_LOGIN_PASSWORD }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: build application
        run: ./gradlew clean check
      - name: publish image to dockerhub
        run: ./gradlew -Dorg.guardiandevelopment.docker.password=${DOCKER_LOGIN_PASSWORD} publishDocker